spring.application.name=LearnAuthentication
server.port=9090

# Keep DB config from application.properties; this profile focuses on auth mode.
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8181/realms/spring-keycloak-realm}

# Actuator paths stay same as default profile.
management.endpoints.web.base-path=/monitoring
management.endpoints.enabled-by-default=false
management.endpoint.health.enabled=true
management.endpoint.info.enabled=true
management.endpoints.web.exposure.include=health,info
